In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sb

In [2]:
df = pd.read_csv('/home/sh0brun/Documents/Untitled Folder/train.csv')
cleanData = df.copy()

def changeToNol(val):
    return 0 if (pd.isna(val) or (val == "NA") or (val == 'None')  ) else val
for field in df.columns:
    cleanData[field] = df[field].apply(changeToNol)
print(cleanData)

        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave     0      Reg
1        2          20       RL         80.0     9600   Pave     0      Reg
2        3          60       RL         68.0    11250   Pave     0      IR1
3        4          70       RL         60.0     9550   Pave     0      IR1
4        5          60       RL         84.0    14260   Pave     0      IR1
5        6          50       RL         85.0    14115   Pave     0      IR1
6        7          20       RL         75.0    10084   Pave     0      Reg
7        8          60       RL          0.0    10382   Pave     0      IR1
8        9          50       RM         51.0     6120   Pave     0      Reg
9       10         190       RL         50.0     7420   Pave     0      Reg
10      11          20       RL         70.0    11200   Pave     0      Reg
11      12          60       RL         85.0    11924   Pave     0      IR1
12      13          20       RL          0.0    12968   Pave     0      IR2
13      14          20       RL         91.0    10652   Pave     0      IR1
14      15          20       RL          0.0    10920   Pave     0      IR1
15      16          45       RM         51.0     6120   Pave     0      Reg
16      17          20       RL          0.0    11241   Pave     0      IR1
17      18          90       RL         72.0    10791   Pave     0      Reg
18      19          20       RL         66.0    13695   Pave     0      Reg
19      20          20       RL         70.0     7560   Pave     0      Reg
20      21          60       RL        101.0    14215   Pave     0      IR1
21      22          45       RM         57.0     7449   Pave  Grvl      Reg
22      23          20       RL         75.0     9742   Pave     0      Reg
23      24         120       RM         44.0     4224   Pave     0      Reg
24      25          20       RL          0.0     8246   Pave     0      IR1
25      26          20       RL        110.0    14230   Pave     0      Reg
26      27          20       RL         60.0     7200   Pave     0      Reg
27      28          20       RL         98.0    11478   Pave     0      Reg
28      29          20       RL         47.0    16321   Pave     0      IR1
29      30          30       RM         60.0     6324   Pave     0      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1430  1431          60       RL         60.0    21930   Pave     0      IR3
1431  1432         120       RL          0.0     4928   Pave     0      IR1
1432  1433          30       RL         60.0    10800   Pave  Grvl      Reg
1433  1434          60       RL         93.0    10261   Pave     0      IR1
1434  1435          20       RL         80.0    17400   Pave     0      Reg
1435  1436          20       RL         80.0     8400   Pave     0      Reg
1436  1437          20       RL         60.0     9000   Pave     0      Reg
1437  1438          20       RL         96.0    12444   Pave     0      Reg
1438  1439          20       RM         90.0     7407   Pave     0      Reg
1439  1440          60       RL         80.0    11584   Pave     0      Reg
1440  1441          70       RL         79.0    11526   Pave     0      IR1
1441  1442         120       RM          0.0     4426   Pave     0      Reg
1442  1443          60       FV         85.0    11003   Pave     0      Reg
1443  1444          30       RL          0.0     8854   Pave     0      Reg
1444  1445          20       RL         63.0     8500   Pave     0      Reg
1445  1446          85       RL         70.0     8400   Pave     0      Reg
1446  1447          20       RL          0.0    26142   Pave     0      IR1
1447  1448          60       RL         80.0    10000   Pave     0      Reg
1448  1449          50       RL         70.0    11767   Pave     0      Reg
1449  1450         180       RM         21.0     1533   Pave     0      Reg
1450  1451          90       RL         60.0     9000   Pave     0      Reg
1451  1452          20       RL         78.0     9262   Pave     0      Reg
1452  1453         180       RM         35.0     3675   Pave     0      Reg
1453  1454          20       RL         90.0    17217   Pave     0      Reg
1454  1455          20       FV         62.0     7500   Pave  Pave      Reg
1455  1456          60       RL         62.0     7917   Pave     0      Reg
1456  1457          20       RL         85.0    13175   Pave     0      Reg
1457  1458          70       RL         66.0     9042   Pave     0      Reg
1458  1459          20       RL         68.0     9717   Pave     0      Reg
1459  1460          20       RL         75.0     9937   Pave     0      Reg

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0      0      0           0       0
1            Lvl    AllPub  ...        0      0      0           0       0
2            Lvl    AllPub  ...        0      0      0           0       0
3            Lvl    AllPub  ...        0      0      0           0       0
4            Lvl    AllPub  ...        0      0      0           0       0
5            Lvl    AllPub  ...        0      0  MnPrv        Shed     700
6            Lvl    AllPub  ...        0      0      0           0       0
7            Lvl    AllPub  ...        0      0      0        Shed     350
8            Lvl    AllPub  ...        0      0      0           0       0
9            Lvl    AllPub  ...        0      0      0           0       0
10           Lvl    AllPub  ...        0      0      0           0       0
11           Lvl    AllPub  ...        0      0      0           0       0
12           Lvl    AllPub  ...        0      0      0           0       0
13           Lvl    AllPub  ...        0      0      0           0       0
14           Lvl    AllPub  ...        0      0   GdWo           0       0
15           Lvl    AllPub  ...        0      0  GdPrv           0       0
16           Lvl    AllPub  ...        0      0      0        Shed     700
17           Lvl    AllPub  ...        0      0      0        Shed     500
18           Lvl    AllPub  ...        0      0      0           0       0
19           Lvl    AllPub  ...        0      0  MnPrv           0       0
20           Lvl    AllPub  ...        0      0      0           0       0
21           Bnk    AllPub  ...        0      0  GdPrv           0       0
22           Lvl    AllPub  ...        0      0      0           0       0
23           Lvl    AllPub  ...        0      0      0           0       0
24           Lvl    AllPub  ...        0      0  MnPrv           0       0
25           Lvl    AllPub  ...        0      0      0           0       0
26           Lvl    AllPub  ...        0      0      0           0       0
27           Lvl    AllPub  ...        0      0      0           0       0
28           Lvl    AllPub  ...        0      0      0           0       0
29           Lvl    AllPub  ...        0      0      0           0       0
...          ...       ...  ...      ...    ...    ...         ...     ...
1430         Lvl    AllPub  ...        0      0      0           0       0
1431         Lvl    AllPub  ...        0      0      0           0       0
1432         Lvl    AllPub  ...        0      0      0           0       0
1433         Lvl    AllPub  ...        0      0      0           0       0
1434         Low    AllPub  ...        0      0      0           0       0
1435         Lvl    AllPub  ...        0      0  GdPrv           0       0
1436         Lvl    AllPub  ...        0      0   GdWo           0       0
1437         Lvl    AllPub  ...        0      0      0           0       0
1438         Lvl    AllPub  ...        0      0  MnPrv           0       0
1439         Lvl    AllPub  ...        0      0      0           0       0
1440         Bnk    AllPub  ...        0      0      0           0       0
1441         Lvl    AllPub  ...        0      0      0           0       0
1442         Lvl    AllPub  ...        0      0      0           0       0
1443         Lvl    AllPub  ...        0      0      0           0       0
1444         Lvl    AllPub  ...        0      0      0           0       0
1445         Lvl    AllPub  ...        0      0      0           0       0
1446         Lvl    AllPub  ...        0      0      0           0       0
1447         Lvl    AllPub  ...        0      0      0           0       0
1448         Lvl    AllPub  ...        0      0   GdWo           0       0
1449         Lvl    AllPub  ...        0      0      0           0       0
1450         Lvl    AllPub  ...        0      0      0           0       0
1451         Lvl    AllPub  ...        0      0      0           0       0
1452         Lvl    AllPub  ...        0      0      0           0       0
1453         Lvl    AllPub  ...        0      0      0           0       0
1454         Lvl    AllPub  ...        0      0      0           0       0
1455         Lvl    AllPub  ...        0      0      0           0       0
1456         Lvl    AllPub  ...        0      0  MnPrv           0       0
1457         Lvl    AllPub  ...        0      0  GdPrv        Shed    2500
1458         Lvl    AllPub  ...        0      0      0           0       0
1459         Lvl    AllPub  ...        0      0      0           0       0

     MoSold YrSold  SaleType  SaleCondition  SalePrice
0         2   2008        WD         Normal     208500
1         5   2007        WD         Normal     181500
2         9   2008        WD         Normal     223500
3         2   2006        WD        Abnorml     140000
4        12   2008        WD         Normal     250000
5        10   2009        WD         Normal     143000
6         8   2007        WD         Normal     307000
7        11   2009        WD         Normal     200000
8         4   2008        WD        Abnorml     129900
9         1   2008        WD         Normal     118000
10        2   2008        WD         Normal     129500
11        7   2006       New        Partial     345000
12        9   2008        WD         Normal     144000
13        8   2007       New        Partial     279500
14        5   2008        WD         Normal     157000
15        7   2007        WD         Normal     132000
16        3   2010        WD         Normal     149000
17       10   2006        WD         Normal      90000
18        6   2008        WD         Normal     159000
19        5   2009       COD        Abnorml     139000
20       11   2006       New        Partial     325300
21        6   2007        WD         Normal     139400
22        9   2008        WD         Normal     230000
23        6   2007        WD         Normal     129900
24        5   2010        WD         Normal     154000
25        7   2009        WD         Normal     256300
26        5   2010        WD         Normal     134800
27        5   2010        WD         Normal     306000
28       12   2006        WD         Normal     207500
29        5   2008        WD         Normal      68500
...     ...    ...       ...            ...        ...
1430      7   2006        WD         Normal     192140
1431     10   2009        WD         Normal     143750
1432      8   2007        WD         Normal      64500
1433      5   2008        WD         Normal     186500
1434      5   2006        WD         Normal     160000
1435      7   2008       COD        Abnorml     174000
1436      5   2007        WD         Normal     120500
1437     11   2008       New        Partial     394617
1438      4   2010        WD         Normal     149700
1439     11   2007        WD         Normal     197000
1440      9   2008        WD         Normal     191000
1441      5   2008        WD         Normal     149300
1442      4   2009        WD         Normal     310000
1443      5   2009        WD         Normal     121000
1444     11   2007        WD         Normal     179600
1445      5   2007        WD         Normal     129000
1446      4   2010        WD         Normal     157900
1447     12   2007        WD         Normal     240000
1448      5   2007        WD         Normal     112000
1449      8   2006        WD        Abnorml      92000
1450      9   2009        WD         Normal     136000
1451      5   2009       New        Partial     287090
1452      5   2006        WD         Normal     145000
1453      7   2006        WD        Abnorml      84500
1454     10   2009        WD         Normal     185000
1455      8   2007        WD         Normal     175000
1456      2   2010        WD         Normal     210000
1457      5   2010        WD         Normal     266500
1458      4   2010        WD         Normal     142125
1459      6   2008        WD         Normal     147500

[1460 rows x 81 columns]

In [3]:
#define new value
defining_value = cleanData.copy()
dict_value = []
def transform_data(val):
#     print(val)
    if(val==0): 
        return 0
    if(dict_value.count(val)>0):
        _index = dict_value.index(val)+1
    else :
        _index = len(dict_value)+1
        dict_value.append(val)
    return _index

for field in ['Street','Alley','LotShape','LandContour','Utilities','LotConfig','LandSlope','Neighborhood','Condition1',
             'Condition2','BldgType','HouseStyle','RoofStyle','RoofMatl','Exterior1st','Exterior2nd','MasVnrType',
             'ExterQual','ExterCond','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2',
             'BsmtFinType2','Heating','HeatingQC','CentralAir','Electrical','KitchenQual','Functional','FireplaceQu',
              'GarageType','GarageFinish','GarageQual','GarageCond','PavedDrive','PoolQC','Fence','MiscFeature',
              'SaleType','SaleCondition','MSZoning'
             ]:
    dict_value = []
    defining_value[field] = cleanData[field].apply(transform_data)
    
# print(defining_value['Alley'])

In [4]:
sub = df[['LotFrontage','LotArea','SalePrice','MSSubClass','MasVnrArea']]

In [5]:
print(sub)

      LotFrontage  LotArea  SalePrice  MSSubClass  MasVnrArea
0            65.0     8450     208500          60       196.0
1            80.0     9600     181500          20         0.0
2            68.0    11250     223500          60       162.0
3            60.0     9550     140000          70         0.0
4            84.0    14260     250000          60       350.0
5            85.0    14115     143000          50         0.0
6            75.0    10084     307000          20       186.0
7             NaN    10382     200000          60       240.0
8            51.0     6120     129900          50         0.0
9            50.0     7420     118000         190         0.0
10           70.0    11200     129500          20         0.0
11           85.0    11924     345000          60       286.0
12            NaN    12968     144000          20         0.0
13           91.0    10652     279500          20       306.0
14            NaN    10920     157000          20       212.0
15           51.0     6120     132000          45         0.0
16            NaN    11241     149000          20       180.0
17           72.0    10791      90000          90         0.0
18           66.0    13695     159000          20         0.0
19           70.0     7560     139000          20         0.0
20          101.0    14215     325300          60       380.0
21           57.0     7449     139400          45         0.0
22           75.0     9742     230000          20       281.0
23           44.0     4224     129900         120         0.0
24            NaN     8246     154000          20         0.0
25          110.0    14230     256300          20       640.0
26           60.0     7200     134800          20         0.0
27           98.0    11478     306000          20       200.0
28           47.0    16321     207500          20         0.0
29           60.0     6324      68500          30         0.0
...           ...      ...        ...         ...         ...
1430         60.0    21930     192140          60         0.0
1431          NaN     4928     143750         120         0.0
1432         60.0    10800      64500          30         0.0
1433         93.0    10261     186500          60       318.0
1434         80.0    17400     160000          20         0.0
1435         80.0     8400     174000          20       237.0
1436         60.0     9000     120500          20         0.0
1437         96.0    12444     394617          20       426.0
1438         90.0     7407     149700          20         0.0
1439         80.0    11584     197000          60        96.0
1440         79.0    11526     191000          70         0.0
1441          NaN     4426     149300         120       147.0
1442         85.0    11003     310000          60       160.0
1443          NaN     8854     121000          30         0.0
1444         63.0     8500     179600          20       106.0
1445         70.0     8400     129000          85         0.0
1446          NaN    26142     157900          20       189.0
1447         80.0    10000     240000          60       438.0
1448         70.0    11767     112000          50         0.0
1449         21.0     1533      92000         180         0.0
1450         60.0     9000     136000          90         0.0
1451         78.0     9262     287090          20       194.0
1452         35.0     3675     145000         180        80.0
1453         90.0    17217      84500          20         0.0
1454         62.0     7500     185000          20         0.0
1455         62.0     7917     175000          60         0.0
1456         85.0    13175     210000          20       119.0
1457         66.0     9042     266500          70         0.0
1458         68.0     9717     142125          20         0.0
1459         75.0     9937     147500          20         0.0

[1460 rows x 5 columns]

In [6]:
sub = sub.dropna()

In [7]:
print(sub)

      LotFrontage  LotArea  SalePrice  MSSubClass  MasVnrArea
0            65.0     8450     208500          60       196.0
1            80.0     9600     181500          20         0.0
2            68.0    11250     223500          60       162.0
3            60.0     9550     140000          70         0.0
4            84.0    14260     250000          60       350.0
5            85.0    14115     143000          50         0.0
6            75.0    10084     307000          20       186.0
8            51.0     6120     129900          50         0.0
9            50.0     7420     118000         190         0.0
10           70.0    11200     129500          20         0.0
11           85.0    11924     345000          60       286.0
13           91.0    10652     279500          20       306.0
15           51.0     6120     132000          45         0.0
17           72.0    10791      90000          90         0.0
18           66.0    13695     159000          20         0.0
19           70.0     7560     139000          20         0.0
20          101.0    14215     325300          60       380.0
21           57.0     7449     139400          45         0.0
22           75.0     9742     230000          20       281.0
23           44.0     4224     129900         120         0.0
25          110.0    14230     256300          20       640.0
26           60.0     7200     134800          20         0.0
27           98.0    11478     306000          20       200.0
28           47.0    16321     207500          20         0.0
29           60.0     6324      68500          30         0.0
30           50.0     8500      40000          70         0.0
32           85.0    11049     179900          20         0.0
33           70.0    10552     165500          20         0.0
34           60.0     7313     277500         120       246.0
35          108.0    13418     309000          60       132.0
...           ...      ...        ...         ...         ...
1425         80.0    10721     142000          20       243.0
1426         81.0    10944     271000          60       448.0
1427         60.0    10930     140000          50         0.0
1428         60.0     7200     119000          30       294.0
1430         60.0    21930     192140          60         0.0
1432         60.0    10800      64500          30         0.0
1433         93.0    10261     186500          60       318.0
1434         80.0    17400     160000          20         0.0
1435         80.0     8400     174000          20       237.0
1436         60.0     9000     120500          20         0.0
1437         96.0    12444     394617          20       426.0
1438         90.0     7407     149700          20         0.0
1439         80.0    11584     197000          60        96.0
1440         79.0    11526     191000          70         0.0
1442         85.0    11003     310000          60       160.0
1444         63.0     8500     179600          20       106.0
1445         70.0     8400     129000          85         0.0
1447         80.0    10000     240000          60       438.0
1448         70.0    11767     112000          50         0.0
1449         21.0     1533      92000         180         0.0
1450         60.0     9000     136000          90         0.0
1451         78.0     9262     287090          20       194.0
1452         35.0     3675     145000         180        80.0
1453         90.0    17217      84500          20         0.0
1454         62.0     7500     185000          20         0.0
1455         62.0     7917     175000          60         0.0
1456         85.0    13175     210000          20       119.0
1457         66.0     9042     266500          70         0.0
1458         68.0     9717     142125          20         0.0
1459         75.0     9937     147500          20         0.0

[1195 rows x 5 columns]

In [8]:
defining_value

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,1,65.0,8450,1,0,1,1,1,...,0,0,0,0,0,2,2008,1,1,208500
1,2,20,1,80.0,9600,1,0,1,1,1,...,0,0,0,0,0,5,2007,1,1,181500
2,3,60,1,68.0,11250,1,0,2,1,1,...,0,0,0,0,0,9,2008,1,1,223500
3,4,70,1,60.0,9550,1,0,2,1,1,...,0,0,0,0,0,2,2006,1,2,140000
4,5,60,1,84.0,14260,1,0,2,1,1,...,0,0,0,0,0,12,2008,1,1,250000
5,6,50,1,85.0,14115,1,0,2,1,1,...,0,0,1,1,700,10,2009,1,1,143000
6,7,20,1,75.0,10084,1,0,1,1,1,...,0,0,0,0,0,8,2007,1,1,307000
7,8,60,1,0.0,10382,1,0,2,1,1,...,0,0,0,1,350,11,2009,1,1,200000
8,9,50,2,51.0,6120,1,0,1,1,1,...,0,0,0,0,0,4,2008,1,2,129900
9,10,190,1,50.0,7420,1,0,1,1,1,...,0,0,0,0,0,1,2008,1,1,118000
10,11,20,1,70.0,11200,1,0,1,1,1,...,0,0,0,0,0,2,2008,1,1,129500
11,12,60,1,85.0,11924,1,0,2,1,1,...,0,0,0,0,0,7,2006,2,3,345000
12,13,20,1,0.0,12968,1,0,3,1,1,...,0,0,0,0,0,9,2008,1,1,144000
13,14,20,1,91.0,10652,1,0,2,1,1,...,0,0,0,0,0,8,2007,2,3,279500
14,15,20,1,0.0,10920,1,0,2,1,1,...,0,0,2,0,0,5,2008,1,1,157000
15,16,45,2,51.0,6120,1,0,1,1,1,...,0,0,3,0,0,7,2007,1,1,132000
16,17,20,1,0.0,11241,1,0,2,1,1,...,0,0,0,1,700,3,2010,1,1,149000
17,18,90,1,72.0,10791,1,0,1,1,1,...,0,0,0,1,500,10,2006,1,1,90000
18,19,20,1,66.0,13695,1,0,1,1,1,...,0,0,0,0,0,6,2008,1,1,159000
19,20,20,1,70.0,7560,1,0,1,1,1,...,0,0,1,0,0,5,2009,3,2,139000
20,21,60,1,101.0,14215,1,0,2,1,1,...,0,0,0,0,0,11,2006,2,3,325300
21,22,45,2,57.0,7449,1,1,1,2,1,...,0,0,3,0,0,6,2007,1,1,139400
22,23,20,1,75.0,9742,1,0,1,1,1,...,0,0,0,0,0,9,2008,1,1,230000
23,24,120,2,44.0,4224,1,0,1,1,1,...,0,0,0,0,0,6,2007,1,1,129900
24,25,20,1,0.0,8246,1,0,2,1,1,...,0,0,1,0,0,5,2010,1,1,154000
25,26,20,1,110.0,14230,1,0,1,1,1,...,0,0,0,0,0,7,2009,1,1,256300
26,27,20,1,60.0,7200,1,0,1,1,1,...,0,0,0,0,0,5,2010,1,1,134800
27,28,20,1,98.0,11478,1,0,1,1,1,...,0,0,0,0,0,5,2010,1,1,306000
28,29,20,1,47.0,16321,1,0,2,1,1,...,0,0,0,0,0,12,2006,1,1,207500
29,30,30,2,60.0,6324,1,0,2,1,1,...,0,0,0,0,0,5,2008,1,1,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,1431,60,1,60.0,21930,1,0,4,1,1,...,0,0,0,0,0,7,2006,1,1,192140
1431,1432,120,1,0.0,4928,1,0,2,1,1,...,0,0,0,0,0,10,2009,1,1,143750
1432,1433,30,1,60.0,10800,1,1,1,1,1,...,0,0,0,0,0,8,2007,1,1,64500
1433,1434,60,1,93.0,10261,1,0,2,1,1,...,0,0,0,0,0,5,2008,1,1,186500
1434,1435,20,1,80.0,17400,1,0,1,3,1,...,0,0,0,0,0,5,2006,1,1,160000
1435,1436,20,1,80.0,8400,1,0,1,1,1,...,0,0,3,0,0,7,2008,3,2,174000
1436,1437,20,1,60.0,9000,1,0,1,1,1,...,0,0,2,0,0,5,2007,1,1,120500
1437,1438,20,1,96.0,12444,1,0,1,1,1,...,0,0,0,0,0,11,2008,2,3,394617
1438,1439,20,2,90.0,7407,1,0,1,1,1,...,0,0,1,0,0,4,2010,1,1,149700
1439,1440,60,1,80.0,11584,1,0,1,1,1,...,0,0,0,0,0,11,2007,1,1,197000
1440,1441,70,1,79.0,11526,1,0,2,2,1,...,0,0,0,0,0,9,2008,1,1,191000
1441,1442,120,2,0.0,4426,1,0,1,1,1,...,0,0,0,0,0,5,2008,1,1,149300
1442,1443,60,4,85.0,11003,1,0,1,1,1,...,0,0,0,0,0,4,2009,1,1,310000
1443,1444,30,1,0.0,8854,1,0,1,1,1,...,0,0,0,0,0,5,2009,1,1,121000
1444,1445,20,1,63.0,8500,1,0,1,1,1,...,0,0,0,0,0,11,2007,1,1,179600
1445,1446,85,1,70.0,8400,1,0,1,1,1,...,0,0,0,0,0,5,2007,1,1,129000
1446,1447,20,1,0.0,26142,1,0,2,1,1,...,0,0,0,0,0,4,2010,1,1,157900
1447,1448,60,1,80.0,10000,1,0,1,1,1,...,0,0,0,0,0,12,2007,1,1,240000
1448,1449,50,1,70.0,11767,1,0,1,1,1,...,0,0,2,0,0,5,2007,1,1,112000
1449,1450,180,2,21.0,1533,1,0,1,1,1,...,0,0,0,0,0,8,2006,1,2,92000
1450,1451,90,1,60.0,9000,1,0,1,1,1,...,0,0,0,0,0,9,2009,1,1,136000
1451,1452,20,1,78.0,9262,1,0,1,1,1,...,0,0,0,0,0,5,2009,2,3,287090
1452,1453,180,2,35.0,3675,1,0,1,1,1,...,0,0,0,0,0,5,2006,1,1,145000
1453,1454,20,1,90.0,17217,1,0,1,1,1,...,0,0,0,0,0,7,2006,1,2,84500
1454,1455,20,4,62.0,7500,1,2,1,1,1,...,0,0,0,0,0,10,2009,1,1,185000
1455,1456,60,1,62.0,7917,1,0,1,1,1,...,0,0,0,0,0,8,2007,1,1,175000
1456,1457,20,1,85.0,13175,1,0,1,1,1,...,0,0,1,0,0,2,2010,1,1,210000
1457,1458,70,1,66.0,9042,1,0,1,1,1,...,0,0,3,1,2500,5,2010,1,1,266500
1458,1459,20,1,68.0,9717,1,0,1,1,1,...,0,0,0,0,0,4,2010,1,1,142125
1459,1460,20,1,75.0,9937,1,0,1,1,1,...,0,0,0,0,0,6,2008,1,1,147500

In [ ]:
sb.pairplot(defining_value[defining_value.columns],diag_kind='kde')